routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\EmailReportController;
use App\Http\Controllers\PrintUserReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/report/guest/{senderId}/{startDate}/{endDate}', [ActivityController::class, 'activityReportForGuest'])->name('report.for.guest');

Route::group(['middleware' => 'auth'], function(){
    Route::post('/email/report', [EmailReportController::class, 'sendReportByEmail'])->name('email.report');
    Route::post('/print-report', [PrintUserReportController::class, 'generatePDF'])->name('print.report');
    Route::resource('activity', ActivityController::class, ['except' => ['create', 'show', 'edit']]);
});

app/Http/Controllers/ActivityController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\User;
use Carbon\CarbonPeriod;
use App\Models\UserActivity;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use App\Http\Requests\ActivityRequest;
use App\Http\Requests\SendReportByEmailRequest;

class ActivityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $weekStartDate = now()->startOfWeek()->format('Y-m-d');
        $weekEndDate = now()->endOfWeek()->format('Y-m-d');

        if($request->start_date && $request->end_date)
        {
            $weekStartDate = $request->start_date;
            $weekEndDate = $request->end_date;
        }

        $activities = auth()->user()->activities()->whereBetween('activity_date', [$weekStartDate, $weekEndDate])->get();

        return view('activity.index', [
            'activities' => $activities,
            'weekStartDate' => $weekStartDate,
            'weekEndDate' => $weekEndDate
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ActivityRequest $request)
    {
        UserActivity::create($request->validated() + [
            'user_id' => Auth::id(),
        ]);

        return redirect(route('activity.index'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ActivityRequest $request, $id)
    {
        $userActivity = UserActivity::find($id);
        $userActivity->update($request->validated());

        return redirect(route('activity.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $userActivity = UserActivity::find($id)->delete();

        if($userActivity)
        {
            return redirect(route('activity.index'))->with('success', 'Activity deleted.');
        } 
        else 
        {
            return redirect(route('activity.index'))->with('error', 'Something went wrong.');
        }

    }

    public function activityReportForGuest($senderId, $startDate, $endDate)
    {
        $user = User::find(Crypt::decrypt($senderId));
        $activities = $user->activities()->whereBetween('activity_date', [Crypt::decrypt($startDate), Crypt::decrypt($endDate)])->get();

        return view('report_for_guest', ['activities' => $activities]);
    }

}

resources/views/activity/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-3 d-flex justify-content-between">
                <div>
                    <h3>{{ __('Activities') }}</h3>
                </div>
                <div class="btn-toolbar">
                    <div class="mr-1">
                        <button class="btn btn-primary" data-toggle="modal" data-target="#create-activity-modal">Add activity</button>
                    </div>
                    <div class="mr-1">
                        <button class="btn btn-info" data-toggle="modal" data-target="#send-report-modal">Send Report</button>
                    </div>
                    <form action="{{route('print.report')}}" method="POST">
                        @csrf
                        <input type="hidden" name="start_date" value="{{$weekStartDate}}">
                        <input type="hidden" name="end_date" value="{{$weekEndDate}}">
                        <button type="submit" class="btn btn-info">Print Report</button>
                    </form>
                </div>
            </div>
            @include('partials.error_handling')
        </div>
        <div class="row">
            <div class="col-md-12">
                <div>
                    <form action="{{route('activity.index')}}" method="GET" class="d-flex">
                        <div style="width: 40%; margin-right: 10px;">
                            <label for="start-date">Start Date</label>
                            <input type="date" name="start_date" value="{{$weekStartDate}}" class="form-control" id="start-date" required>
                        </div>
                        <div style="width: 40%; margin-right: 10px;">
                            <label for="end-date">End Date</label>
                            <input type="date" name="end_date" value="{{$weekEndDate}}" class="form-control" id="end-date" required>
                        </div>
                        <div class="align-self-end float-right ml-auto">
                            <button type="submit" class="btn btn-primary">Go</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            @forelse ($activities as $activity)
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="py-3">
                    <div class="card">
                        <div class="card-body card-activity-body">
                            <h4>Activity Date</h4>
                            <p>{{$activity->activity_date}}</p>
                            <h4>Time Spent</h4>
                            <p>{{$activity->time_spent}} h</p>
                            <h4>Description</h4>
                            <p>{{$activity->description}}</p>
                        </div>
                        <?php $activity->description = str_replace(array("\n", "\r"), ' ', $activity->description); ?>
                        <div class="card-footer">
                            <button class="btn btn-info" onclick="editActivityModal('{{route('activity.update', $activity->id)}}', '{{$activity->activity_date}}', '{{$activity->time_spent}}', '{{$activity->description}}')">Edit</button>
                            <button class="btn btn-danger" onclick="deleteActivityModal('{{route('activity.destroy', $activity->id)}}', '{{$activity->id}}')">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
            @empty
                <div class="mt-3">
                    <h5>There are no activities!</h5>
                </div>
            @endforelse
        </div>
    </div>

    
@endsection
<x-modals.create_activity/>
<x-modals.edit_activity />
<x-modals.delete_activity />
<x-modals.send_activity_report :weekStartDate="$weekStartDate" :weekEndDate="$weekEndDate"/>

resources/views/activity/print-report.blade.php
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Scripts -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
        <div id="app">
            <main class="py-4">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div>
                                <table class="table table-striped text-center">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Total hours spent on any activity</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($userActivityData as $date => $totalHours)
                                            <tr>
                                                <td>{{$date}}</td>
                                                <td>{{$totalHours}} h</td>                                                
                                            </tr>
                                        @endforeach
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Total hours for all days</th>
                                            <th>{{$totalSumForTheInterval}} h</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </body>
</html>